# Generated by Django 2.2.7 on 2019-11-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
