# Generated by Django 2.2.7 on 2019-11-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoitem_iscomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='isComplete',
            new_name='is_complete',
        ),
    ]
