# Generated by Django 2.2.7 on 2019-11-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20191112_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='bucketId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='todo.BucketItem'),
        ),
    ]
