# Generated by Django 2.2.7 on 2019-11-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20191112_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='bucketId',
            field=models.IntegerField(null=True),
        ),
    ]
