# Generated by Django 2.2.7 on 2019-11-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_bucketitem_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='bucketId',
            new_name='bucket_Id',
        ),
    ]
